#!/bin/bash
[[ $(screen -list| grep -c 'bot_teste') == '0' ]] && {
    clear
    echo -e "\E[44;1;37m     ATIVACÃO BOT SSH TESTE     \E[0m"
    echo ""
    echo -ne "\n\033[1;32mINFORME O TOKEN\033[1;37m: "
    read token
    clear
    echo ""
    echo -e "\033[1;32mINICIANDO BOT TESTE \033[0m\n"
    cd $HOME/BOT
    rm -rf $HOME/BOT/botssh
    wget https://www.dropbox.com/scl/fi/ynqkx282zpzw3qevsocwu/botssh?rlkey=9yvg9okaru3qa4sfz1re8m3pz >/dev/null 2>&1
    rm -rf $HOME/ShellBot.sh
    wget https://www.dropbox.com/scl/fi/u5ol9f9d90wh0o28i3urp/ShellBot.sh?rlkey=v6wpk54rnddtouj1wu3xsosic >/dev/null 2>&1
    chmod 777 botssh 
    chmod 777 ShellBot.sh
    echo ""
    sleep 1
    screen -dmS bot_teste ./botssh $token > /dev/null 2>&1
    clear
    echo "BOT ATIVADO"
    menu
} || {
    screen -r -S "bot_teste" -X quit
    clear
    echo "BOT DESATIVADO"
    menu
}
